name: "@iwsio/mongodb-express-session: PR to main"

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'package/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
  
jobs:
  tests:
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
    uses: iwsllc/workflows/.github/workflows/test.yaml@v2
    with:
      node-version: ${{ matrix.node-version }}
      install-command: npm ci -w package
      test-command: npm test -w package
