name: "@iwsio/mongodb-express-session: PR to main"

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'package/**'

jobs:
  run-tests:
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/test.yaml@v2
    with:
      scope: '@iwsio'
      node-version-file: '.nvmrc'
      install-command: npm ci
      test-command: npm run test
