name: "@iwsio/mongodb-express-session: PR to main"

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'package/**'

jobs:
  run_tests:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/mongodb-session-test.yaml
